version: "3"

services:
  database-flashcard:
    image: postgres:alpine
    restart: always
    network_mode: bridge
    expose:
      - 3032
    ports:
      - "3032:5432"
    volumes:
      - flashcarddata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=flashcard_service
  testDb:
    image: postgres:alpine
    restart: always
    expose:
      - 6033
    ports:
      - "6033:5432"
    volumes:
      - testdata:/var/lib/postgresql/testdata
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test_data
  app-flashcard:
    build: .
    restart: always
    network_mode: bridge
    container_name: flashcard_service
    expose:
      - 3000
      - 3001
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - database-flashcard
    links:
      - database-flashcard
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database-flashcard:5432/flashcard_service
volumes:
  flashcarddata:

